steps:
  - name: "docker"
    args: ["build", "-t", "gcr.io/sacom-dev/flask-app", "./services/web"]

# By default, all built docker images will be lost once the build is complete.
# Rather than writing a build step to push this image, you can simply list the
# image below and it will automatically be uploaded to Google Cloud Container
# Registry.
images:
  - "gcr.io/sacom-dev/flask-app"

# You can organize your builds with tags
tags: ["latest"]
# You can configure more options than the ones listed here. Visit
# https://cloud.google.com/cloud-build/docs/build-config to see the full list of
# available options.
